PACKAGE_NAME="mt7668"
PACKAGE_VERSION="1.0.3"
BUILT_MODULE_NAME[0]="wlan_mt7668"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless/mediatek/mt7668"
MAKE[0]="make -j$(nproc) KERNELRELEASE=$kernelver -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build CONFIG_CC_HAS_MIN_FUNCTION_ALIGNMENT="
AUTOINSTALL="yes"
